// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_tokens.sql

package store

import (
	"context"
)

const deleteAIToken = `-- name: DeleteAIToken :exec
DELETE FROM ai_tokens WHERE user_id=$1
`

func (q *Queries) DeleteAIToken(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteAIToken, userID)
	return err
}

const getAIToken = `-- name: GetAIToken :one
SELECT id, user_id, provider, token_ciphertext, token_nonce, created_at, updated_at FROM ai_tokens WHERE user_id=$1
`

func (q *Queries) GetAIToken(ctx context.Context, userID int64) (AiToken, error) {
	row := q.db.QueryRow(ctx, getAIToken, userID)
	var i AiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.TokenCiphertext,
		&i.TokenNonce,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAIToken = `-- name: UpsertAIToken :one
INSERT INTO ai_tokens (user_id, provider, token_ciphertext, token_nonce)
VALUES ($1,$2,$3,$4)
ON CONFLICT (user_id) DO UPDATE
  SET provider=EXCLUDED.provider,
      token_ciphertext=EXCLUDED.token_ciphertext,
      token_nonce=EXCLUDED.token_nonce,
      updated_at=now()
RETURNING id, user_id, provider, token_ciphertext, token_nonce, created_at, updated_at
`

type UpsertAITokenParams struct {
	UserID          int64  `json:"user_id"`
	Provider        string `json:"provider"`
	TokenCiphertext []byte `json:"token_ciphertext"`
	TokenNonce      []byte `json:"token_nonce"`
}

func (q *Queries) UpsertAIToken(ctx context.Context, arg UpsertAITokenParams) (AiToken, error) {
	row := q.db.QueryRow(ctx, upsertAIToken,
		arg.UserID,
		arg.Provider,
		arg.TokenCiphertext,
		arg.TokenNonce,
	)
	var i AiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.TokenCiphertext,
		&i.TokenNonce,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
