// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attempts.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeAttempt = `-- name: CompleteAttempt :one
UPDATE student_attempts SET pontos=$2, concluido_em=now() WHERE id=$1 RETURNING id, study_trail_id, nome_aluno, pontos, concluido_em, created_at, student_id
`

type CompleteAttemptParams struct {
	ID     int64 `json:"id"`
	Pontos int32 `json:"pontos"`
}

func (q *Queries) CompleteAttempt(ctx context.Context, arg CompleteAttemptParams) (StudentAttempt, error) {
	row := q.db.QueryRow(ctx, completeAttempt, arg.ID, arg.Pontos)
	var i StudentAttempt
	err := row.Scan(
		&i.ID,
		&i.StudyTrailID,
		&i.NomeAluno,
		&i.Pontos,
		&i.ConcluidoEm,
		&i.CreatedAt,
		&i.StudentID,
	)
	return i, err
}

const createAttempt = `-- name: CreateAttempt :one
INSERT INTO student_attempts (study_trail_id, nome_aluno, student_id) VALUES ($1,$2,$3) RETURNING id, study_trail_id, nome_aluno, pontos, concluido_em, created_at, student_id
`

type CreateAttemptParams struct {
	StudyTrailID int64  `json:"study_trail_id"`
	NomeAluno    string `json:"nome_aluno"`
	StudentID    *int64 `json:"student_id"`
}

func (q *Queries) CreateAttempt(ctx context.Context, arg CreateAttemptParams) (StudentAttempt, error) {
	row := q.db.QueryRow(ctx, createAttempt, arg.StudyTrailID, arg.NomeAluno, arg.StudentID)
	var i StudentAttempt
	err := row.Scan(
		&i.ID,
		&i.StudyTrailID,
		&i.NomeAluno,
		&i.Pontos,
		&i.ConcluidoEm,
		&i.CreatedAt,
		&i.StudentID,
	)
	return i, err
}

const getAttempt = `-- name: GetAttempt :one
SELECT id, study_trail_id, nome_aluno, pontos, concluido_em, created_at, student_id FROM student_attempts WHERE id=$1
`

func (q *Queries) GetAttempt(ctx context.Context, id int64) (StudentAttempt, error) {
	row := q.db.QueryRow(ctx, getAttempt, id)
	var i StudentAttempt
	err := row.Scan(
		&i.ID,
		&i.StudyTrailID,
		&i.NomeAluno,
		&i.Pontos,
		&i.ConcluidoEm,
		&i.CreatedAt,
		&i.StudentID,
	)
	return i, err
}

const insertAnswer = `-- name: InsertAnswer :exec
INSERT INTO attempt_answers (student_attempt_id, quiz_question_id, escolhida, correta)
VALUES ($1,$2,$3,$4)
`

type InsertAnswerParams struct {
	StudentAttemptID int64 `json:"student_attempt_id"`
	QuizQuestionID   int64 `json:"quiz_question_id"`
	Escolhida        int32 `json:"escolhida"`
	Correta          bool  `json:"correta"`
}

func (q *Queries) InsertAnswer(ctx context.Context, arg InsertAnswerParams) error {
	_, err := q.db.Exec(ctx, insertAnswer,
		arg.StudentAttemptID,
		arg.QuizQuestionID,
		arg.Escolhida,
		arg.Correta,
	)
	return err
}

const trailStats = `-- name: TrailStats :many
SELECT nome_aluno, pontos, concluido_em, created_at
FROM student_attempts WHERE study_trail_id=$1 ORDER BY created_at DESC
`

type TrailStatsRow struct {
	NomeAluno   string             `json:"nome_aluno"`
	Pontos      int32              `json:"pontos"`
	ConcluidoEm pgtype.Timestamptz `json:"concluido_em"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) TrailStats(ctx context.Context, studyTrailID int64) ([]TrailStatsRow, error) {
	rows, err := q.db.Query(ctx, trailStats, studyTrailID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrailStatsRow
	for rows.Next() {
		var i TrailStatsRow
		if err := rows.Scan(
			&i.NomeAluno,
			&i.Pontos,
			&i.ConcluidoEm,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
