// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bncc.sql

package store

import (
	"context"
)

const countBnccSkills = `-- name: CountBnccSkills :one
SELECT count(*) FROM bncc_skills
`

func (q *Queries) CountBnccSkills(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBnccSkills)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBnccSkill = `-- name: GetBnccSkill :one
SELECT id, code, disciplina, ano, descricao, assunto FROM bncc_skills WHERE id = $1
`

func (q *Queries) GetBnccSkill(ctx context.Context, id int64) (BnccSkill, error) {
	row := q.db.QueryRow(ctx, getBnccSkill, id)
	var i BnccSkill
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Disciplina,
		&i.Ano,
		&i.Descricao,
		&i.Assunto,
	)
	return i, err
}

const insertBnccSkill = `-- name: InsertBnccSkill :exec
INSERT INTO bncc_skills (code, disciplina, ano, assunto, descricao)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (code) DO UPDATE SET
  disciplina = EXCLUDED.disciplina,
  ano = EXCLUDED.ano,
  assunto = EXCLUDED.assunto,
  descricao = EXCLUDED.descricao
`

type InsertBnccSkillParams struct {
	Code       string `json:"code"`
	Disciplina string `json:"disciplina"`
	Ano        string `json:"ano"`
	Assunto    string `json:"assunto"`
	Descricao  string `json:"descricao"`
}

func (q *Queries) InsertBnccSkill(ctx context.Context, arg InsertBnccSkillParams) error {
	_, err := q.db.Exec(ctx, insertBnccSkill,
		arg.Code,
		arg.Disciplina,
		arg.Ano,
		arg.Assunto,
		arg.Descricao,
	)
	return err
}

const listBnccSkills = `-- name: ListBnccSkills :many
SELECT id, code, disciplina, ano, descricao, assunto FROM bncc_skills
WHERE ($1::text = '' OR disciplina = $1)
  AND ($2::text = '' OR ano = $2)
  AND ($3::text = '' OR assunto = $3)
ORDER BY disciplina, ano, code
`

type ListBnccSkillsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 string `json:"column_3"`
}

func (q *Queries) ListBnccSkills(ctx context.Context, arg ListBnccSkillsParams) ([]BnccSkill, error) {
	rows, err := q.db.Query(ctx, listBnccSkills, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BnccSkill
	for rows.Next() {
		var i BnccSkill
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Disciplina,
			&i.Ano,
			&i.Descricao,
			&i.Assunto,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
