// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bncc.sql

package store

import (
	"context"
)

const countBnccSkills = `-- name: CountBnccSkills :one
SELECT count(*) FROM bncc_skills
`

func (q *Queries) CountBnccSkills(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBnccSkills)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBnccSkill = `-- name: GetBnccSkill :one
SELECT id, code, disciplina, descricao, assunto, etapa, anos FROM bncc_skills WHERE id = $1
`

func (q *Queries) GetBnccSkill(ctx context.Context, id int64) (BnccSkill, error) {
	row := q.db.QueryRow(ctx, getBnccSkill, id)
	var i BnccSkill
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Disciplina,
		&i.Descricao,
		&i.Assunto,
		&i.Etapa,
		&i.Anos,
	)
	return i, err
}

const insertBnccSkill = `-- name: InsertBnccSkill :exec
INSERT INTO bncc_skills (code, etapa, disciplina, anos, assunto, descricao)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (code) DO UPDATE SET
  etapa = EXCLUDED.etapa,
  disciplina = EXCLUDED.disciplina,
  anos = EXCLUDED.anos,
  assunto = EXCLUDED.assunto,
  descricao = EXCLUDED.descricao
`

type InsertBnccSkillParams struct {
	Code       string  `json:"code"`
	Etapa      string  `json:"etapa"`
	Disciplina string  `json:"disciplina"`
	Anos       []int32 `json:"anos"`
	Assunto    string  `json:"assunto"`
	Descricao  string  `json:"descricao"`
}

func (q *Queries) InsertBnccSkill(ctx context.Context, arg InsertBnccSkillParams) error {
	_, err := q.db.Exec(ctx, insertBnccSkill,
		arg.Code,
		arg.Etapa,
		arg.Disciplina,
		arg.Anos,
		arg.Assunto,
		arg.Descricao,
	)
	return err
}

const listBnccSkills = `-- name: ListBnccSkills :many
SELECT id, code, disciplina, descricao, assunto, etapa, anos FROM bncc_skills
WHERE ($1::text = '' OR etapa = $1)
  AND ($2::text = '' OR disciplina = $2)
  AND (
    $3::text = ''
    OR code ILIKE '%' || $3 || '%'
    OR disciplina ILIKE '%' || $3 || '%'
    OR assunto ILIKE '%' || $3 || '%'
    OR descricao ILIKE '%' || $3 || '%'
  )
ORDER BY etapa, disciplina, code
`

type ListBnccSkillsParams struct {
	Etapa      string `json:"etapa"`
	Disciplina string `json:"disciplina"`
	Q          string `json:"q"`
}

func (q *Queries) ListBnccSkills(ctx context.Context, arg ListBnccSkillsParams) ([]BnccSkill, error) {
	rows, err := q.db.Query(ctx, listBnccSkills, arg.Etapa, arg.Disciplina, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BnccSkill
	for rows.Next() {
		var i BnccSkill
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Disciplina,
			&i.Descricao,
			&i.Assunto,
			&i.Etapa,
			&i.Anos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
