// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lessons.sql

package store

import (
	"context"
)

const createLessonPlan = `-- name: CreateLessonPlan :one
INSERT INTO lesson_plans
  (user_id, bncc_skill_id, duracao_min, origem, status, objetivos, metodologia, recursos, avaliacao, atividade)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id, user_id, bncc_skill_id, duracao_min, origem, status, objetivos, metodologia, recursos, avaliacao, atividade, created_at, updated_at
`

type CreateLessonPlanParams struct {
	UserID      int64  `json:"user_id"`
	BnccSkillID *int64 `json:"bncc_skill_id"`
	DuracaoMin  int32  `json:"duracao_min"`
	Origem      string `json:"origem"`
	Status      string `json:"status"`
	Objetivos   string `json:"objetivos"`
	Metodologia string `json:"metodologia"`
	Recursos    string `json:"recursos"`
	Avaliacao   string `json:"avaliacao"`
	Atividade   string `json:"atividade"`
}

func (q *Queries) CreateLessonPlan(ctx context.Context, arg CreateLessonPlanParams) (LessonPlan, error) {
	row := q.db.QueryRow(ctx, createLessonPlan,
		arg.UserID,
		arg.BnccSkillID,
		arg.DuracaoMin,
		arg.Origem,
		arg.Status,
		arg.Objetivos,
		arg.Metodologia,
		arg.Recursos,
		arg.Avaliacao,
		arg.Atividade,
	)
	var i LessonPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BnccSkillID,
		&i.DuracaoMin,
		&i.Origem,
		&i.Status,
		&i.Objetivos,
		&i.Metodologia,
		&i.Recursos,
		&i.Avaliacao,
		&i.Atividade,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLessonPlan = `-- name: GetLessonPlan :one
SELECT id, user_id, bncc_skill_id, duracao_min, origem, status, objetivos, metodologia, recursos, avaliacao, atividade, created_at, updated_at FROM lesson_plans WHERE id=$1
`

func (q *Queries) GetLessonPlan(ctx context.Context, id int64) (LessonPlan, error) {
	row := q.db.QueryRow(ctx, getLessonPlan, id)
	var i LessonPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BnccSkillID,
		&i.DuracaoMin,
		&i.Origem,
		&i.Status,
		&i.Objetivos,
		&i.Metodologia,
		&i.Recursos,
		&i.Avaliacao,
		&i.Atividade,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLessonPlansByUser = `-- name: ListLessonPlansByUser :many
SELECT id, user_id, bncc_skill_id, duracao_min, origem, status, objetivos, metodologia, recursos, avaliacao, atividade, created_at, updated_at FROM lesson_plans WHERE user_id=$1 ORDER BY created_at DESC
`

func (q *Queries) ListLessonPlansByUser(ctx context.Context, userID int64) ([]LessonPlan, error) {
	rows, err := q.db.Query(ctx, listLessonPlansByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LessonPlan
	for rows.Next() {
		var i LessonPlan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BnccSkillID,
			&i.DuracaoMin,
			&i.Origem,
			&i.Status,
			&i.Objetivos,
			&i.Metodologia,
			&i.Recursos,
			&i.Avaliacao,
			&i.Atividade,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLessonStatus = `-- name: SetLessonStatus :exec
UPDATE lesson_plans SET status=$2, updated_at=now() WHERE id=$1
`

type SetLessonStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetLessonStatus(ctx context.Context, arg SetLessonStatusParams) error {
	_, err := q.db.Exec(ctx, setLessonStatus, arg.ID, arg.Status)
	return err
}

const updateLessonPlan = `-- name: UpdateLessonPlan :one
UPDATE lesson_plans SET
  bncc_skill_id=$2, duracao_min=$3, objetivos=$4, metodologia=$5,
  recursos=$6, avaliacao=$7, atividade=$8, origem=$9, updated_at=now()
WHERE id=$1 RETURNING id, user_id, bncc_skill_id, duracao_min, origem, status, objetivos, metodologia, recursos, avaliacao, atividade, created_at, updated_at
`

type UpdateLessonPlanParams struct {
	ID          int64  `json:"id"`
	BnccSkillID *int64 `json:"bncc_skill_id"`
	DuracaoMin  int32  `json:"duracao_min"`
	Objetivos   string `json:"objetivos"`
	Metodologia string `json:"metodologia"`
	Recursos    string `json:"recursos"`
	Avaliacao   string `json:"avaliacao"`
	Atividade   string `json:"atividade"`
	Origem      string `json:"origem"`
}

func (q *Queries) UpdateLessonPlan(ctx context.Context, arg UpdateLessonPlanParams) (LessonPlan, error) {
	row := q.db.QueryRow(ctx, updateLessonPlan,
		arg.ID,
		arg.BnccSkillID,
		arg.DuracaoMin,
		arg.Objetivos,
		arg.Metodologia,
		arg.Recursos,
		arg.Avaliacao,
		arg.Atividade,
		arg.Origem,
	)
	var i LessonPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BnccSkillID,
		&i.DuracaoMin,
		&i.Origem,
		&i.Status,
		&i.Objetivos,
		&i.Metodologia,
		&i.Recursos,
		&i.Avaliacao,
		&i.Atividade,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
