// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AttemptAnswer struct {
	ID               int64 `json:"id"`
	StudentAttemptID int64 `json:"student_attempt_id"`
	QuizQuestionID   int64 `json:"quiz_question_id"`
	Escolhida        int32 `json:"escolhida"`
	Correta          bool  `json:"correta"`
}

type BnccSkill struct {
	ID         int64  `json:"id"`
	Code       string `json:"code"`
	Disciplina string `json:"disciplina"`
	Ano        string `json:"ano"`
	Descricao  string `json:"descricao"`
	Assunto    string `json:"assunto"`
}

type LessonPlan struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	BnccSkillID *int64             `json:"bncc_skill_id"`
	DuracaoMin  int32              `json:"duracao_min"`
	Origem      string             `json:"origem"`
	Status      string             `json:"status"`
	Objetivos   string             `json:"objetivos"`
	Metodologia string             `json:"metodologia"`
	Recursos    string             `json:"recursos"`
	Avaliacao   string             `json:"avaliacao"`
	Atividade   string             `json:"atividade"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Quiz struct {
	ID           int64 `json:"id"`
	StudyTrailID int64 `json:"study_trail_id"`
}

type QuizQuestion struct {
	ID        int64  `json:"id"`
	QuizID    int64  `json:"quiz_id"`
	Ordem     int32  `json:"ordem"`
	Enunciado string `json:"enunciado"`
	Opcoes    []byte `json:"opcoes"`
	Correta   int32  `json:"correta"`
}

type Session struct {
	ID        string             `json:"id"`
	UserID    int64              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type StudentAttempt struct {
	ID           int64              `json:"id"`
	StudyTrailID int64              `json:"study_trail_id"`
	NomeAluno    string             `json:"nome_aluno"`
	Pontos       int32              `json:"pontos"`
	ConcluidoEm  pgtype.Timestamptz `json:"concluido_em"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type StudyTrail struct {
	ID           int64              `json:"id"`
	LessonPlanID int64              `json:"lesson_plan_id"`
	Codigo       *string            `json:"codigo"`
	PublicadaEm  pgtype.Timestamptz `json:"publicada_em"`
}

type TrailTopic struct {
	ID           int64  `json:"id"`
	StudyTrailID int64  `json:"study_trail_id"`
	Ordem        int32  `json:"ordem"`
	Titulo       string `json:"titulo"`
	Resumo       string `json:"resumo"`
}

type User struct {
	ID        int64              `json:"id"`
	Email     string             `json:"email"`
	SenhaHash string             `json:"senha_hash"`
	Nome      string             `json:"nome"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
