// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quiz.sql

package store

import (
	"context"
)

const createQuiz = `-- name: CreateQuiz :one
INSERT INTO quizzes (study_trail_id) VALUES ($1)
ON CONFLICT (study_trail_id) DO UPDATE SET study_trail_id=EXCLUDED.study_trail_id
RETURNING id, study_trail_id
`

func (q *Queries) CreateQuiz(ctx context.Context, studyTrailID int64) (Quiz, error) {
	row := q.db.QueryRow(ctx, createQuiz, studyTrailID)
	var i Quiz
	err := row.Scan(&i.ID, &i.StudyTrailID)
	return i, err
}

const deleteQuestionsByQuiz = `-- name: DeleteQuestionsByQuiz :exec
DELETE FROM quiz_questions WHERE quiz_id=$1
`

func (q *Queries) DeleteQuestionsByQuiz(ctx context.Context, quizID int64) error {
	_, err := q.db.Exec(ctx, deleteQuestionsByQuiz, quizID)
	return err
}

const getQuizByTrail = `-- name: GetQuizByTrail :one
SELECT id, study_trail_id FROM quizzes WHERE study_trail_id=$1
`

func (q *Queries) GetQuizByTrail(ctx context.Context, studyTrailID int64) (Quiz, error) {
	row := q.db.QueryRow(ctx, getQuizByTrail, studyTrailID)
	var i Quiz
	err := row.Scan(&i.ID, &i.StudyTrailID)
	return i, err
}

const insertQuestion = `-- name: InsertQuestion :exec
INSERT INTO quiz_questions (quiz_id, ordem, enunciado, opcoes, correta) VALUES ($1,$2,$3,$4,$5)
`

type InsertQuestionParams struct {
	QuizID    int64  `json:"quiz_id"`
	Ordem     int32  `json:"ordem"`
	Enunciado string `json:"enunciado"`
	Opcoes    []byte `json:"opcoes"`
	Correta   int32  `json:"correta"`
}

func (q *Queries) InsertQuestion(ctx context.Context, arg InsertQuestionParams) error {
	_, err := q.db.Exec(ctx, insertQuestion,
		arg.QuizID,
		arg.Ordem,
		arg.Enunciado,
		arg.Opcoes,
		arg.Correta,
	)
	return err
}

const listQuestions = `-- name: ListQuestions :many
SELECT id, quiz_id, ordem, enunciado, opcoes, correta FROM quiz_questions WHERE quiz_id=$1 ORDER BY ordem
`

func (q *Queries) ListQuestions(ctx context.Context, quizID int64) ([]QuizQuestion, error) {
	rows, err := q.db.Query(ctx, listQuestions, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuizQuestion
	for rows.Next() {
		var i QuizQuestion
		if err := rows.Scan(
			&i.ID,
			&i.QuizID,
			&i.Ordem,
			&i.Enunciado,
			&i.Opcoes,
			&i.Correta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsPublic = `-- name: ListQuestionsPublic :many
SELECT id, ordem, enunciado, opcoes FROM quiz_questions WHERE quiz_id=$1 ORDER BY ordem
`

type ListQuestionsPublicRow struct {
	ID        int64  `json:"id"`
	Ordem     int32  `json:"ordem"`
	Enunciado string `json:"enunciado"`
	Opcoes    []byte `json:"opcoes"`
}

func (q *Queries) ListQuestionsPublic(ctx context.Context, quizID int64) ([]ListQuestionsPublicRow, error) {
	rows, err := q.db.Query(ctx, listQuestionsPublic, quizID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuestionsPublicRow
	for rows.Next() {
		var i ListQuestionsPublicRow
		if err := rows.Scan(
			&i.ID,
			&i.Ordem,
			&i.Enunciado,
			&i.Opcoes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
