// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: student_sessions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStudentSession = `-- name: CreateStudentSession :one
INSERT INTO student_sessions (id, student_id, expires_at) VALUES ($1,$2,$3) RETURNING id, student_id, expires_at, created_at
`

type CreateStudentSessionParams struct {
	ID        string             `json:"id"`
	StudentID int64              `json:"student_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateStudentSession(ctx context.Context, arg CreateStudentSessionParams) (StudentSession, error) {
	row := q.db.QueryRow(ctx, createStudentSession, arg.ID, arg.StudentID, arg.ExpiresAt)
	var i StudentSession
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStudentSession = `-- name: DeleteStudentSession :exec
DELETE FROM student_sessions WHERE id=$1
`

func (q *Queries) DeleteStudentSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteStudentSession, id)
	return err
}

const getStudentSession = `-- name: GetStudentSession :one
SELECT id, student_id, expires_at, created_at FROM student_sessions WHERE id=$1 AND expires_at > now()
`

func (q *Queries) GetStudentSession(ctx context.Context, id string) (StudentSession, error) {
	row := q.db.QueryRow(ctx, getStudentSession, id)
	var i StudentSession
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
