// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: students.sql

package store

import (
	"context"
)

const createStudent = `-- name: CreateStudent :one
INSERT INTO students (turma_id, nome, usuario, senha_hash, matricula)
VALUES ($1,$2,$3,$4,$5) RETURNING id, turma_id, nome, usuario, senha_hash, matricula, created_at
`

type CreateStudentParams struct {
	TurmaID   int64   `json:"turma_id"`
	Nome      string  `json:"nome"`
	Usuario   string  `json:"usuario"`
	SenhaHash string  `json:"senha_hash"`
	Matricula *string `json:"matricula"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRow(ctx, createStudent,
		arg.TurmaID,
		arg.Nome,
		arg.Usuario,
		arg.SenhaHash,
		arg.Matricula,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.TurmaID,
		&i.Nome,
		&i.Usuario,
		&i.SenhaHash,
		&i.Matricula,
		&i.CreatedAt,
	)
	return i, err
}

const getStudent = `-- name: GetStudent :one
SELECT id, turma_id, nome, usuario, senha_hash, matricula, created_at FROM students WHERE id=$1
`

func (q *Queries) GetStudent(ctx context.Context, id int64) (Student, error) {
	row := q.db.QueryRow(ctx, getStudent, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.TurmaID,
		&i.Nome,
		&i.Usuario,
		&i.SenhaHash,
		&i.Matricula,
		&i.CreatedAt,
	)
	return i, err
}

const getStudentByUsuario = `-- name: GetStudentByUsuario :one
SELECT id, turma_id, nome, usuario, senha_hash, matricula, created_at FROM students WHERE usuario=$1
`

func (q *Queries) GetStudentByUsuario(ctx context.Context, usuario string) (Student, error) {
	row := q.db.QueryRow(ctx, getStudentByUsuario, usuario)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.TurmaID,
		&i.Nome,
		&i.Usuario,
		&i.SenhaHash,
		&i.Matricula,
		&i.CreatedAt,
	)
	return i, err
}

const listStudentsByTurma = `-- name: ListStudentsByTurma :many
SELECT id, turma_id, nome, usuario, senha_hash, matricula, created_at FROM students WHERE turma_id=$1 ORDER BY nome
`

func (q *Queries) ListStudentsByTurma(ctx context.Context, turmaID int64) ([]Student, error) {
	rows, err := q.db.Query(ctx, listStudentsByTurma, turmaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.TurmaID,
			&i.Nome,
			&i.Usuario,
			&i.SenhaHash,
			&i.Matricula,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudentPassword = `-- name: UpdateStudentPassword :exec
UPDATE students SET senha_hash=$2 WHERE id=$1
`

type UpdateStudentPasswordParams struct {
	ID        int64  `json:"id"`
	SenhaHash string `json:"senha_hash"`
}

func (q *Queries) UpdateStudentPassword(ctx context.Context, arg UpdateStudentPasswordParams) error {
	_, err := q.db.Exec(ctx, updateStudentPassword, arg.ID, arg.SenhaHash)
	return err
}
