// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trails.sql

package store

import (
	"context"
)

const createTrail = `-- name: CreateTrail :one
INSERT INTO study_trails (lesson_plan_id) VALUES ($1) RETURNING id, lesson_plan_id, codigo, publicada_em, turma_id
`

func (q *Queries) CreateTrail(ctx context.Context, lessonPlanID int64) (StudyTrail, error) {
	row := q.db.QueryRow(ctx, createTrail, lessonPlanID)
	var i StudyTrail
	err := row.Scan(
		&i.ID,
		&i.LessonPlanID,
		&i.Codigo,
		&i.PublicadaEm,
		&i.TurmaID,
	)
	return i, err
}

const deleteTopics = `-- name: DeleteTopics :exec
DELETE FROM trail_topics WHERE study_trail_id=$1
`

func (q *Queries) DeleteTopics(ctx context.Context, studyTrailID int64) error {
	_, err := q.db.Exec(ctx, deleteTopics, studyTrailID)
	return err
}

const getTrailByCode = `-- name: GetTrailByCode :one
SELECT id, lesson_plan_id, codigo, publicada_em, turma_id FROM study_trails WHERE codigo=$1
`

func (q *Queries) GetTrailByCode(ctx context.Context, codigo *string) (StudyTrail, error) {
	row := q.db.QueryRow(ctx, getTrailByCode, codigo)
	var i StudyTrail
	err := row.Scan(
		&i.ID,
		&i.LessonPlanID,
		&i.Codigo,
		&i.PublicadaEm,
		&i.TurmaID,
	)
	return i, err
}

const getTrailByLesson = `-- name: GetTrailByLesson :one
SELECT id, lesson_plan_id, codigo, publicada_em, turma_id FROM study_trails WHERE lesson_plan_id=$1
`

func (q *Queries) GetTrailByLesson(ctx context.Context, lessonPlanID int64) (StudyTrail, error) {
	row := q.db.QueryRow(ctx, getTrailByLesson, lessonPlanID)
	var i StudyTrail
	err := row.Scan(
		&i.ID,
		&i.LessonPlanID,
		&i.Codigo,
		&i.PublicadaEm,
		&i.TurmaID,
	)
	return i, err
}

const insertTopic = `-- name: InsertTopic :exec
INSERT INTO trail_topics (study_trail_id, ordem, titulo, resumo) VALUES ($1,$2,$3,$4)
`

type InsertTopicParams struct {
	StudyTrailID int64  `json:"study_trail_id"`
	Ordem        int32  `json:"ordem"`
	Titulo       string `json:"titulo"`
	Resumo       string `json:"resumo"`
}

func (q *Queries) InsertTopic(ctx context.Context, arg InsertTopicParams) error {
	_, err := q.db.Exec(ctx, insertTopic,
		arg.StudyTrailID,
		arg.Ordem,
		arg.Titulo,
		arg.Resumo,
	)
	return err
}

const listTopics = `-- name: ListTopics :many
SELECT id, study_trail_id, ordem, titulo, resumo FROM trail_topics WHERE study_trail_id=$1 ORDER BY ordem
`

func (q *Queries) ListTopics(ctx context.Context, studyTrailID int64) ([]TrailTopic, error) {
	rows, err := q.db.Query(ctx, listTopics, studyTrailID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrailTopic
	for rows.Next() {
		var i TrailTopic
		if err := rows.Scan(
			&i.ID,
			&i.StudyTrailID,
			&i.Ordem,
			&i.Titulo,
			&i.Resumo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishTrail = `-- name: PublishTrail :one
UPDATE study_trails SET codigo=$2, publicada_em=now() WHERE id=$1 RETURNING id, lesson_plan_id, codigo, publicada_em, turma_id
`

type PublishTrailParams struct {
	ID     int64   `json:"id"`
	Codigo *string `json:"codigo"`
}

func (q *Queries) PublishTrail(ctx context.Context, arg PublishTrailParams) (StudyTrail, error) {
	row := q.db.QueryRow(ctx, publishTrail, arg.ID, arg.Codigo)
	var i StudyTrail
	err := row.Scan(
		&i.ID,
		&i.LessonPlanID,
		&i.Codigo,
		&i.PublicadaEm,
		&i.TurmaID,
	)
	return i, err
}

const setTrailTurma = `-- name: SetTrailTurma :exec
UPDATE study_trails SET turma_id=$2 WHERE id=$1
`

type SetTrailTurmaParams struct {
	ID      int64  `json:"id"`
	TurmaID *int64 `json:"turma_id"`
}

func (q *Queries) SetTrailTurma(ctx context.Context, arg SetTrailTurmaParams) error {
	_, err := q.db.Exec(ctx, setTrailTurma, arg.ID, arg.TurmaID)
	return err
}
