// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: turmas.sql

package store

import (
	"context"
)

const createTurma = `-- name: CreateTurma :one
INSERT INTO turmas (user_id, nome, etapa, anos) VALUES ($1,$2,$3,$4) RETURNING id, user_id, nome, etapa, anos, created_at
`

type CreateTurmaParams struct {
	UserID int64   `json:"user_id"`
	Nome   string  `json:"nome"`
	Etapa  string  `json:"etapa"`
	Anos   []int32 `json:"anos"`
}

func (q *Queries) CreateTurma(ctx context.Context, arg CreateTurmaParams) (Turma, error) {
	row := q.db.QueryRow(ctx, createTurma,
		arg.UserID,
		arg.Nome,
		arg.Etapa,
		arg.Anos,
	)
	var i Turma
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nome,
		&i.Etapa,
		&i.Anos,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTurma = `-- name: DeleteTurma :exec
DELETE FROM turmas WHERE id=$1
`

func (q *Queries) DeleteTurma(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTurma, id)
	return err
}

const getTurma = `-- name: GetTurma :one
SELECT id, user_id, nome, etapa, anos, created_at FROM turmas WHERE id=$1
`

func (q *Queries) GetTurma(ctx context.Context, id int64) (Turma, error) {
	row := q.db.QueryRow(ctx, getTurma, id)
	var i Turma
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nome,
		&i.Etapa,
		&i.Anos,
		&i.CreatedAt,
	)
	return i, err
}

const listTurmasByUser = `-- name: ListTurmasByUser :many
SELECT id, user_id, nome, etapa, anos, created_at FROM turmas WHERE user_id=$1 ORDER BY created_at DESC
`

func (q *Queries) ListTurmasByUser(ctx context.Context, userID int64) ([]Turma, error) {
	rows, err := q.db.Query(ctx, listTurmasByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Turma
	for rows.Next() {
		var i Turma
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Nome,
			&i.Etapa,
			&i.Anos,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTurma = `-- name: UpdateTurma :one
UPDATE turmas SET nome=$2, etapa=$3, anos=$4 WHERE id=$1 RETURNING id, user_id, nome, etapa, anos, created_at
`

type UpdateTurmaParams struct {
	ID    int64   `json:"id"`
	Nome  string  `json:"nome"`
	Etapa string  `json:"etapa"`
	Anos  []int32 `json:"anos"`
}

func (q *Queries) UpdateTurma(ctx context.Context, arg UpdateTurmaParams) (Turma, error) {
	row := q.db.QueryRow(ctx, updateTurma,
		arg.ID,
		arg.Nome,
		arg.Etapa,
		arg.Anos,
	)
	var i Turma
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Nome,
		&i.Etapa,
		&i.Anos,
		&i.CreatedAt,
	)
	return i, err
}
