// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: turma_lessons.sql

package store

import (
	"context"
)

const attachTurmaLesson = `-- name: AttachTurmaLesson :one
INSERT INTO turma_lessons (turma_id, lesson_plan_id, ordem)
VALUES ($1, $2, COALESCE((SELECT max(ordem) FROM turma_lessons WHERE turma_id=$1), 0) + 1)
RETURNING id, turma_id, lesson_plan_id, ordem, created_at
`

type AttachTurmaLessonParams struct {
	TurmaID      int64 `json:"turma_id"`
	LessonPlanID int64 `json:"lesson_plan_id"`
}

func (q *Queries) AttachTurmaLesson(ctx context.Context, arg AttachTurmaLessonParams) (TurmaLesson, error) {
	row := q.db.QueryRow(ctx, attachTurmaLesson, arg.TurmaID, arg.LessonPlanID)
	var i TurmaLesson
	err := row.Scan(
		&i.ID,
		&i.TurmaID,
		&i.LessonPlanID,
		&i.Ordem,
		&i.CreatedAt,
	)
	return i, err
}

const detachTurmaLesson = `-- name: DetachTurmaLesson :exec
DELETE FROM turma_lessons WHERE turma_id=$1 AND lesson_plan_id=$2
`

type DetachTurmaLessonParams struct {
	TurmaID      int64 `json:"turma_id"`
	LessonPlanID int64 `json:"lesson_plan_id"`
}

func (q *Queries) DetachTurmaLesson(ctx context.Context, arg DetachTurmaLessonParams) error {
	_, err := q.db.Exec(ctx, detachTurmaLesson, arg.TurmaID, arg.LessonPlanID)
	return err
}

const listStudentTurmaLessons = `-- name: ListStudentTurmaLessons :many
SELECT tl.lesson_plan_id, tl.ordem, st.codigo,
       COALESCE(bs.assunto, 'Aula #' || lp.id::text) AS label,
       COALESCE(sa.pontos, 0)::int AS pontos,
       (sa.concluido_em IS NOT NULL)::boolean AS concluido
FROM turma_lessons tl
JOIN lesson_plans lp ON lp.id = tl.lesson_plan_id
LEFT JOIN study_trails st ON st.lesson_plan_id = lp.id
LEFT JOIN bncc_skills bs ON bs.id = lp.bncc_skill_id
LEFT JOIN LATERAL (
  SELECT sa.pontos, sa.concluido_em
  FROM student_attempts sa
  WHERE sa.study_trail_id = st.id
    AND sa.student_id = $1
    AND sa.concluido_em IS NOT NULL
  ORDER BY sa.concluido_em DESC
  LIMIT 1
) sa ON true
WHERE tl.turma_id = $2
ORDER BY tl.ordem
`

type ListStudentTurmaLessonsParams struct {
	StudentID *int64 `json:"student_id"`
	TurmaID   int64  `json:"turma_id"`
}

type ListStudentTurmaLessonsRow struct {
	LessonPlanID int64   `json:"lesson_plan_id"`
	Ordem        int32   `json:"ordem"`
	Codigo       *string `json:"codigo"`
	Label        string  `json:"label"`
	Pontos       int32   `json:"pontos"`
	Concluido    bool    `json:"concluido"`
}

func (q *Queries) ListStudentTurmaLessons(ctx context.Context, arg ListStudentTurmaLessonsParams) ([]ListStudentTurmaLessonsRow, error) {
	rows, err := q.db.Query(ctx, listStudentTurmaLessons, arg.StudentID, arg.TurmaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStudentTurmaLessonsRow
	for rows.Next() {
		var i ListStudentTurmaLessonsRow
		if err := rows.Scan(
			&i.LessonPlanID,
			&i.Ordem,
			&i.Codigo,
			&i.Label,
			&i.Pontos,
			&i.Concluido,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTurmaLessons = `-- name: ListTurmaLessons :many
SELECT tl.lesson_plan_id, tl.ordem, lp.status, st.codigo,
       COALESCE(bs.assunto, 'Aula #' || lp.id::text) AS label
FROM turma_lessons tl
JOIN lesson_plans lp ON lp.id = tl.lesson_plan_id
LEFT JOIN study_trails st ON st.lesson_plan_id = lp.id
LEFT JOIN bncc_skills bs ON bs.id = lp.bncc_skill_id
WHERE tl.turma_id = $1
ORDER BY tl.ordem
`

type ListTurmaLessonsRow struct {
	LessonPlanID int64   `json:"lesson_plan_id"`
	Ordem        int32   `json:"ordem"`
	Status       string  `json:"status"`
	Codigo       *string `json:"codigo"`
	Label        string  `json:"label"`
}

func (q *Queries) ListTurmaLessons(ctx context.Context, turmaID int64) ([]ListTurmaLessonsRow, error) {
	rows, err := q.db.Query(ctx, listTurmaLessons, turmaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTurmaLessonsRow
	for rows.Next() {
		var i ListTurmaLessonsRow
		if err := rows.Scan(
			&i.LessonPlanID,
			&i.Ordem,
			&i.Status,
			&i.Codigo,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renumberTurmaLessons = `-- name: RenumberTurmaLessons :exec
WITH ordered AS (
  SELECT id, row_number() OVER (ORDER BY ordem) AS rn
  FROM turma_lessons tl2 WHERE tl2.turma_id=$1
)
UPDATE turma_lessons tl SET ordem = ordered.rn
FROM ordered WHERE tl.id = ordered.id
`

func (q *Queries) RenumberTurmaLessons(ctx context.Context, turmaID int64) error {
	_, err := q.db.Exec(ctx, renumberTurmaLessons, turmaID)
	return err
}

const setTurmaLessonOrder = `-- name: SetTurmaLessonOrder :exec
UPDATE turma_lessons tl
SET ordem = data.ord
FROM (
  SELECT unnest($2::bigint[]) AS lesson_plan_id,
         generate_subscripts($2::bigint[], 1) AS ord
) data
WHERE tl.turma_id = $1 AND tl.lesson_plan_id = data.lesson_plan_id
`

type SetTurmaLessonOrderParams struct {
	TurmaID       int64   `json:"turma_id"`
	LessonPlanIds []int64 `json:"lesson_plan_ids"`
}

func (q *Queries) SetTurmaLessonOrder(ctx context.Context, arg SetTurmaLessonOrderParams) error {
	_, err := q.db.Exec(ctx, setTurmaLessonOrder, arg.TurmaID, arg.LessonPlanIds)
	return err
}
