// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, senha_hash, nome) VALUES ($1,$2,$3) RETURNING id, email, senha_hash, nome, created_at
`

type CreateUserParams struct {
	Email     string `json:"email"`
	SenhaHash string `json:"senha_hash"`
	Nome      string `json:"nome"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.SenhaHash, arg.Nome)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.SenhaHash,
		&i.Nome,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, senha_hash, nome, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.SenhaHash,
		&i.Nome,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, senha_hash, nome, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.SenhaHash,
		&i.Nome,
		&i.CreatedAt,
	)
	return i, err
}
